apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
spec:
  storageClassName: wordpress-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
